<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQk3zKJu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQk3zKJu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQk3zKJu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQk3zKJu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQk3zKJu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qk3zKJu',
    'container.build_id' => '4530ae6a',
    'container.build_time' => 1617964253,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQk3zKJu');
