<?php

namespace ContainerQk3zKJu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KnXTvrGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.knXTvrG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.knXTvrG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encode' => ['privates', 'App\\Service\\EncodeService', 'getEncodeServiceService', true],
        ], [
            'encode' => 'App\\Service\\EncodeService',
        ]);
    }
}
