<?php

namespace ContainerQk3zKJu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncodeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EncodeService' shared autowired service.
     *
     * @return \App\Service\EncodeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EncodeService.php';

        return $container->privates['App\\Service\\EncodeService'] = new \App\Service\EncodeService(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));
    }
}
